# Generated by Django 4.1.5 on 2024-08-04 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(default=" ", max_length=255)),
                ("last_name", models.CharField(default=" ", max_length=255)),
                ("personal_id", models.CharField(default=" ", max_length=255)),
                (
                    "social_security_number",
                    models.CharField(default=" ", max_length=255),
                ),
                ("father_name", models.CharField(default=" ", max_length=255)),
                ("address", models.TextField(default="")),
                ("city", models.TextField(default="")),
                ("phone_number_1", models.CharField(default="", max_length=15)),
                (
                    "phone_number_2",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "phone_number_3",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        default="default_images/PL.jpg", upload_to="profile_pictures/"
                    ),
                ),
                (
                    "agent_level",
                    models.CharField(
                        choices=[("اول", "اول"), ("دوم", "دوم"), ("رزرو", "رزرو")],
                        default=" ",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.TextField(default="")),
                ("sender_address", models.TextField(default="")),
                ("receiver_address", models.TextField(default="")),
                (
                    "description",
                    models.CharField(
                        choices=[
                            ("هوایی", "هوایی"),
                            ("پایانه اتوبوسرانی", "پایانه اتوبوسرانی"),
                            ("پایانه تاکسیرانی", "پایانه تاکسیرانی"),
                            ("خود شخص", "خود شخص"),
                        ],
                        max_length=40,
                    ),
                ),
                ("box_number", models.CharField(max_length=50)),
                ("sender_phone_number", models.CharField(max_length=50)),
                ("receiver_phone_number", models.CharField(max_length=50)),
                (
                    "mission_status",
                    models.CharField(
                        choices=[
                            ("انجام نشده", "انجام نشده"),
                            ("در حال ارسال", "در حال ارسال"),
                            ("انجام شد", "انجام شد"),
                        ],
                        default="انجام نشده",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("receive_from", models.CharField(default="", max_length=50)),
                ("receive_from_number", models.CharField(default="", max_length=15)),
                ("receive_at", models.DateTimeField(auto_now=True)),
                ("deliver_to", models.CharField(default="", max_length=50)),
                ("deliver_to_number", models.CharField(default="", max_length=15)),
                ("mission_date", models.DateField(blank=True, null=True)),
                (
                    "assigned_agent",
                    models.ForeignKey(
                        default=" ",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agents.agent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
