# Generated by Django 4.1.5 on 2024-07-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=15)),
                ("image", models.ImageField(upload_to="agents/images/")),
                ("documentation", models.ImageField(upload_to="agents/docs/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
