# Generated by Django 4.1.5 on 2024-08-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mission", old_name="address", new_name="receiver_address",
        ),
        migrations.RemoveField(model_name="mission", name="title",),
        migrations.AddField(
            model_name="mission",
            name="sender_address",
            field=models.TextField(default=""),
        ),
    ]
