# Generated by Django 4.1.5 on 2024-07-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="agent", name="created_at",),
        migrations.AlterField(
            model_name="agent",
            name="documentation",
            field=models.FileField(upload_to="docs/"),
        ),
        migrations.AlterField(
            model_name="agent", name="email", field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="agent",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
