# Generated by Django 4.1.5 on 2024-07-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_remove_agent_created_at_alter_agent_documentation_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agent", old_name="phone", new_name="phone_number_1",
        ),
        migrations.RemoveField(model_name="agent", name="documentation",),
        migrations.RemoveField(model_name="agent", name="email",),
        migrations.RemoveField(model_name="agent", name="image",),
        migrations.RemoveField(model_name="agent", name="name",),
        migrations.AddField(
            model_name="agent", name="address", field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="agent",
            name="agent_level",
            field=models.CharField(
                choices=[("one", "One"), ("two", "Two"), ("reserved", "Reserved")],
                default="reserved",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="birth_certificate_image",
            field=models.ImageField(default="", upload_to="birth_certificates/"),
        ),
        migrations.AddField(
            model_name="agent",
            name="father_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="agent",
            name="first_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="agent",
            name="last_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="agent",
            name="mission_detail",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="agent",
            name="personal_id",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="agent",
            name="phone_number_2",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="phone_number_3",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="profile_picture",
            field=models.ImageField(default="", upload_to="profile_pictures/"),
        ),
        migrations.AddField(
            model_name="agent",
            name="social_security_card_image",
            field=models.ImageField(default="", upload_to="ssn_cards/"),
        ),
        migrations.AddField(
            model_name="agent",
            name="social_security_number",
            field=models.CharField(default="", max_length=255),
        ),
    ]
