# Generated by Django 4.1.5 on 2024-08-04 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_agentimage"),
    ]

    operations = [
        migrations.DeleteModel(name="AgentImage",),
    ]
