# Generated by Django 4.1.5 on 2024-08-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_rename_address_mission_receiver_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="deliver_to",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="mission",
            name="deliver_to_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="mission",
            name="mission_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("انجام نشده", "انجام نشده"),
                    ("درحال ارسال", "در حال ارسال"),
                    ("انجام شد", "انجام شد"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="receive_from",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="mission",
            name="receive_from_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
