# Generated by Django 4.1.5 on 2024-08-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_alter_mission_deliver_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="deliver_to",
            field=models.CharField(default=" ", max_length=50),
        ),
        migrations.AlterField(
            model_name="mission",
            name="deliver_to_number",
            field=models.CharField(default=" ", max_length=15),
        ),
        migrations.AlterField(
            model_name="mission",
            name="mission_status",
            field=models.CharField(
                choices=[
                    ("انجام نشده", "انجام نشده"),
                    ("درحال ارسال", "در حال ارسال"),
                    ("انجام شد", "انجام شد"),
                ],
                default="انجام نشده",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="receive_from",
            field=models.CharField(default=" ", max_length=50),
        ),
        migrations.AlterField(
            model_name="mission",
            name="receive_from_number",
            field=models.CharField(default=" ", max_length=15),
        ),
    ]
