# Generated by Django 4.1.5 on 2024-07-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_rename_phone_agent_phone_number_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent", name="address", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="agent",
            name="agent_level",
            field=models.CharField(
                choices=[("one", "One"), ("two", "Two"), ("reserved", "Reserved")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="birth_certificate_image",
            field=models.ImageField(upload_to="birth_certificates/"),
        ),
        migrations.AlterField(
            model_name="agent",
            name="father_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="agent",
            name="first_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="agent",
            name="last_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="agent", name="mission_detail", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="agent",
            name="personal_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="agent",
            name="profile_picture",
            field=models.ImageField(upload_to="profile_pictures/"),
        ),
        migrations.AlterField(
            model_name="agent",
            name="social_security_card_image",
            field=models.ImageField(upload_to="ssn_cards/"),
        ),
        migrations.AlterField(
            model_name="agent",
            name="social_security_number",
            field=models.CharField(max_length=255),
        ),
    ]
