# Generated by Django 4.1.5 on 2024-08-04 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_delete_agentimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="agent_images/")),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="agents.agent",
                    ),
                ),
            ],
        ),
    ]
