# Generated by Django 4.1.5 on 2024-07-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0004_alter_agent_address_alter_agent_agent_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent", name="city", field=models.TextField(default=""),
        ),
    ]
