# Generated by Django 4.1.5 on 2024-07-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0005_agent_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="agent_level",
            field=models.CharField(
                choices=[("اول", "اول"), ("دوم", "دوم"), ("رزرو", "رزرو")],
                max_length=20,
            ),
        ),
    ]
