# Generated by Django 4.1.5 on 2024-08-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0006_alter_mission_deliver_to_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="deliver_to",
            field=models.CharField(max_length=50),
        ),
    ]
