# Generated by Django 4.1.5 on 2024-07-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0006_alter_agent_agent_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent", name="address", field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="agent",
            name="birth_certificate_image",
            field=models.ImageField(
                default="default_images/PL.jpg", upload_to="birth_certificates/"
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="profile_picture",
            field=models.ImageField(
                default="default_images/PL.jpg", upload_to="profile_pictures/"
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="social_security_card_image",
            field=models.ImageField(
                default="default_images/PL.jpg", upload_to="ssn_cards/"
            ),
        ),
    ]
