# Generated by Django 4.1.5 on 2024-08-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0007_alter_mission_deliver_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="mission_status",
            field=models.CharField(
                choices=[
                    ("انجام نشده", "انجام نشده"),
                    ("در حال ارسال", "در حال ارسال"),
                    ("انجام شد", "انجام شد"),
                ],
                default="انجام نشده",
                max_length=50,
            ),
        ),
    ]
