# Generated by Django 4.1.5 on 2024-08-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0008_alter_mission_mission_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="mission_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
