# Generated by Django 4.1.5 on 2024-08-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0009_mission_mission_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="deliver_to",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="mission",
            name="deliver_to_number",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="mission",
            name="receive_from",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="mission",
            name="receive_from_number",
            field=models.CharField(default="", max_length=15),
        ),
    ]
